/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariobross.pkg1.pkg1;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/mario.gif"))); // NOI18N
        jLabel1.setText("Panel de Agregar Objetos:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/suelo1.png"))); // NOI18N
        jLabel2.setText("suelo");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/pared1.png"))); // NOI18N
        jLabel3.setText("pared");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/kopa1.png"))); // NOI18N
        jLabel4.setText("goomba");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/tortuga1.png"))); // NOI18N
        jLabel5.setText("tortuga");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/ficha1.png"))); // NOI18N
        jLabel6.setText("ficha");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/hongo1.png"))); // NOI18N
        jLabel7.setText("hongo");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/mario1.png"))); // NOI18N
        jLabel8.setText("prinsipal");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/castillo.png"))); // NOI18N
        jLabel9.setText("castillo");

        jTextField1.setText("suelo");

        jTextField2.setText("pared");

        jTextField3.setText("goomba");

        jTextField4.setText("tortuga");

        jTextField5.setText("ficha");

        jTextField6.setText("hongo");

        jTextField7.setText("Mario");

        jTextField8.setText("castillo");

        jLabel10.setText("TIPO OBJETO:");

        jLabel11.setText("NOMBRE: ");

        jButton1.setText("agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("agregar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/siguiente.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel14.setText("Ver Lista:");

        jButton10.setText("Pruevas");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Prueva Matriz");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jButton9)
                                    .addComponent(jButton10)
                                    .addComponent(jButton11))
                                .addGap(49, 49, 49))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//codigo DE IMAGENES''''''''''''''''''''''''''''''''
    //ImageIcon imagenInterna = new javax.swing.ImageIcon(getClass().getResource("/mariobross/Imagenes/lol.gif"));
    //jLabel1.setIcon(imagenInterna);
 //'''''''''''''''''''''''''''''''''''''''''''''''''''
   public static ListaDoble ListaObjetos = new ListaDoble (); //lista De Objetos Agregados
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Boton Agregar Suelo 
        String nombre = jTextField1.getText();//toma la caja1
        int tipo = 1; //pone tipo
        
        //insertar a lista
        //listadoble lista = new listadoble ();
        objeto x = new objeto (nombre, tipo);
        //lista.InsertarObjeto(x);
        
        //lista.insertarCabezaLista(x);
        //int prueba = lista.cabeza.dato.id;
        //System.out.print(prueba);
        
        //lista.visualizar();
        
        ListaObjetos.AgregarAlFinal(x);
        JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Suelo Agregado");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton Agregar Pared
        String nombre = jTextField2.getText();//toma la caja1
        int tipo = 2;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
          JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Pared Agregado");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       // Boton Agregar goomba
        String nombre = jTextField3.getText();//toma la caja1
        int tipo = 3;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
          JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Goomba Agregado");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Boton Agregar tortuga
        String nombre = jTextField4.getText();//toma la caja1
        int tipo = 4;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
 JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Toruga Agregado");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Boton Agregar ficha
        String nombre = jTextField5.getText();//toma la caja1
        int tipo = 5;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
          JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Ficha Agregado");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Boton Agregar hongo
        String nombre = jTextField6.getText();//toma la caja1
        int tipo = 6;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
          JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Hongo Agregado");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Boton Agregar Mario
        String nombre = jTextField7.getText();//toma la caja1
        int tipo = 7;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
          JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Mario Agregado");
        jButton7.setEnabled(false); //bloquea el boton para no agregar mas
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Boton Agregar Castillo
        String nombre = jTextField8.getText();//toma la caja1
        int tipo = 8;//pone tipo
        //Insertar A Lista
         objeto x = new objeto (nombre, tipo); //instancia del Objeto
         ListaObjetos.AgregarAlFinal(x); //Agrega ala lista al Final
          JOptionPane.showMessageDialog(rootPane, "Objeto de Tipo Castillo Agregado");
        jButton8.setEnabled(false); //bloquea el boton para no agregar mas
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // PRUEVAS
        
        /*
        if (!ListaObjetos.esVacia()){
            ListaObjetos.MostrarListaInicioFin();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay datos");
        }
        */
        //----------------PRUEVAS MATRIZ ORTOGONAL---------------
        
        
        //PRUEVAS DE LISTAS EN X Y LISTAS EN Y CON NODOS ORTOGONALES
        //Lista en Y
        System.out.println("----------------");
        System.out.println("LISTA EN Y");
        System.out.println("");
        
        ListaY listay= new ListaY();
        
        //La posicion en X no importa ahorita
        /*
        listay.Insertar(new NodoOrtogonal(555,00,30));
        listay.Insertar(new NodoOrtogonal(44,00,20));
        listay.Insertar(new NodoOrtogonal(3,00,1));
        listay.Insertar(new NodoOrtogonal(2,00,5));
        listay.Insertar(new NodoOrtogonal(1,00,2));
        */
        listay.Recorrer();
        
        //LISTA En X
        
        System.out.println("----------------");
        System.out.println("LISTA EN X");
        System.out.println("");
        
        ListaX listax= new ListaX();
        //La posicion en Y no importa
        /*
        listax.Insertar(new NodoOrtogonal(81,29,0));
        listax.Insertar(new NodoOrtogonal(82,19,0));
        listax.Insertar(new NodoOrtogonal(83,4,0));
        listax.Insertar(new NodoOrtogonal(84,3,0));
        listax.Insertar(new NodoOrtogonal(85,30,0));
        */
        listax.Recorrer();
        System.out.println("");
        //PRUEVAS DE CABECERAS Y LATERALES--------
        //CABEZERAS
        System.out.println("----------------");
        System.out.println("Cabezera (x)");
        System.out.println("");
        
        Cabezeras cabezera=new Cabezeras ();
        
        cabezera.Insertar(new NodoCabezera(3),1);
        cabezera.Insertar(new NodoCabezera(0),1);
        cabezera.Insertar(new NodoCabezera(1),1);
        cabezera.Insertar(new NodoCabezera(5),1);
        cabezera.Insertar(new NodoCabezera(4),1);
        
        cabezera.Recorrer();
        System.out.println("");
        
        cabezera.Existe(5);
        NodoCabezera n;
        n=cabezera.Busqueda(50);
        System.out.println("");
        
        //LATERALES
        System.out.println("----------------");
        System.out.println("Lateral (y)");
        System.out.println("");
        
        Laterales lateral=new Laterales ();
        
        lateral.Insertar(new NodoLateral(20),1);
        lateral.Insertar(new NodoLateral(0),1);
        lateral.Insertar(new NodoLateral(1),1);
        lateral.Insertar(new NodoLateral(5),1);
        lateral.Insertar(new NodoLateral(4),1);
        
        lateral.Recorrer();
        
        lateral.Existe(20);
        NodoLateral n1;
        n1=lateral.Busqueda(50);
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // BOTON SIGUIENTE 
        Eliminar x = new Eliminar ();
        if (!ListaObjetos.esVacia()){ //si la lista no esta vacia
            ListaObjetos.MostrarListaInicioFin(); // Mostrar Objetos de Inicio a Fin
            x.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "No hay datos en la Lista Agregue Elementos");
        }
                
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // PRUEVA MATRIZ ORTOGONAL
        
        MatrizOrtogonal matriz = new MatrizOrtogonal();
        
        String ax = JOptionPane.showInputDialog("Ingrese un numero x: ");
        String ay = JOptionPane.showInputDialog("Ingrese un numero y: ");
        int cordenada1=Integer.parseInt(ax);
        int cordenada2=Integer.parseInt(ay);
        
                ClasePruevas.CrearMatriz(cordenada1, cordenada2);
                ClasePruevas.buscarej();
       
                JOptionPane.showMessageDialog(rootPane, ClasePruevas.buscarej());
                
                //primer nodo de la columna 2
        //NodoCabezera nodo;
        //nodo = matriz.c.Busqueda(2);
        //NodoOrtogonal nodo1;
        //nodo1=nodo.columna.primero.abajo.derecha;
        //System.out.println ("Imprime:"+nodo1.dato);        
         
        ventanalol formulario1=new ventanalol();
        formulario1.setBounds(0,0,1500,1000);
        formulario1.setResizable(false);
        formulario1.setVisible(true);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
